name: Build and push grist image

on:
  workflow_dispatch:
    inputs:
      gristVersion:
        description: 'Grist git version'
        required: true
      imageTag:
        description: 'lasuite/grist docker image tag'
        required: true
      imageVersion:
        description: 'choice between DINUM or ANCT image'
        type: choice
        options:
        - DINUM
        - ANCT
        required: true
      commitSha:
        description: 'Git commit sha to build the image'
        required: true
  schedule:
    - cron: 0 22 * * *

env:
  DOCKER_USER: 1001:127

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "dockerfiles,secrets"
      -
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.event.inputs.commitSha || 'main' }}
      -
        name: Load sops secrets
        uses: rouja/actions-sops@main
        with:
          secret-file: secrets/numerique-gouv/dockerfiles/secrets.enc.env
          age-key: ${{ secrets.SOPS_PRIVATE }}
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        run: echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
      -
        name: Build and push
        run: |
          cd dockerfiles/grist;
          docker build --build-arg "GRIST_VERSION=${{ github.event.inputs.gristVersion || 'latest' }}" \
          --build-arg "BUILD_ENV=${{ github.event.inputs.imageVersion || 'DINUM' }}" \
          --annotation "commitSha=${{ github.event.inputs.commitSha || 'main' }}" \
          --file Dockerfile.custom \
          --push . -t lasuite/grist:${{ github.event.inputs.imageTag || 'latest' }}-${{ github.event.inputs.imageVersion || 'DINUM' }};
